@echo off
echo Aggiornando il codice...
python update_site.py
echo Generando le nuove pagine HTML...
python generate_pages.py
echo Preparando il commit per GitHub...
git add index.html generate_pages.py products/
git commit -m "Aggiunti nuovi prodotti: AI Receptionist, CulinaryRoots, PureHome Suite, Hero-Tale, AI Contract Review, Aegis PM"
echo Effettuando il push su GitHub...
git push
echo Completato! Puoi verificare le modifiche sul sito online.
pause
